apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubia-app-3
  template:
    metadata:
      name: kubia
      labels:
        app: kubia-app-3
    spec:
      containers:
      - image: luksa/kubia:v1
        name: nodejs
        resources:
          requests:
            cpu: 100m