apiVersion: v1
kind: Pod
metadata:
  name: kubia-gpu-ns
spec:
  nodeSelector:
    gpu: "true"
  containers:
  - image: luksa/kubia
    name: kubia
    ports:
    - containerPort: 8080
      hostPort: 9000
      protocol: TCP