apiVersion: v1
kind: Pod
metadata:
  name: kubpod
spec:
  containers:
  - image: luksa/kubia:v1
    name: nodejs
    resources:
      limits:
        cpu: 200m
        memory: 20Mi
      requests:
        cpu: 100m
        memory: 10Mi
