apiVersion: v1
kind: Pod
metadata:
  name: pod-as-user-guest
spec:
  containers:
  - name: main
    image: alpine
    command: ["/bin/sleep", "999999"]
    securityContext:
      runAsUser: 405
    resources:
      requests:
        cpu: 100m
        memory: 10Mi
      limits:
        cpu: 200m
        memory: 40Mi
