apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
  namespace: custom-namespace
spec:
  containers:
  – image: luksa/kubia
    name: kubia4
    ports:
    – containerPort: 8080
      protocol: TCP